// Building Compliance Screening — two-step lookup + eligibility.
//
//   site (city, state, sq ft, property type)
//        │  1. City Lookup:  normalized city+state → Government ID
//        ▼
//   Government ID
//        │  2. Master Ordinances:  Government ID → BBS / Audits / BPS mandates
//        ▼
//   per-category eligibility (active ordinance AND building ≥ the size
//   threshold for its property type), the compliance deadline, and the
//   estimated max yearly penalty.
//
// The two reference tables are committed seeds (src/data/masterOrdinances.js
// and src/data/complianceCityLookup.js), generated by
// scripts/buildComplianceOrdinances.mjs. Callers may pass a replacement pair
// (e.g. a user-uploaded City Lookup + Master Ordinances) to every function.

import MASTER_ORDINANCES from '../data/masterOrdinances.js';
import CITY_LOOKUP from '../data/complianceCityLookup.js';

export const CATEGORIES = ['bbs', 'audits', 'bps'];
export const CATEGORY_LABEL = { bbs: 'BBS', audits: 'Energy Audits', bps: 'BPS' };
// Brand-ish palette matching the example deliverable: BBS blue, Audits
// orange, BPS green (+ utility-feed gold / crimson on page 3).
export const CATEGORY_COLOR = { bbs: '#29ABE2', audits: '#F7941E', bps: '#3DAE2B' };

export function normKey(s) {
  return String(s == null ? '' : s).toLowerCase().replace(/[^a-z0-9]+/g, '');
}

// Index the ordinances list by Government ID once per (list identity).
const _ordIndexCache = new WeakMap();
function ordIndex(ordinances) {
  let m = _ordIndexCache.get(ordinances);
  if (!m) { m = new Map(ordinances.map(g => [g.govId, g])); _ordIndexCache.set(ordinances, m); }
  return m;
}

// Common member-city / alias → the jurisdiction city named in the ordinances,
// so a site whose city is a borough (or a covered municipality) still resolves
// to the governing jurisdiction. This is a curated stopgap for the derived
// City Lookup — the real City Lookup tab would carry these mappings directly.
export const CITY_ALIASES = {
  // New York City boroughs all fall under the NYC ordinances.
  brooklyn: 'New York', bronx: 'New York', queens: 'New York',
  statenisland: 'New York', manhattan: 'New York',
  newyorkcity: 'New York', nyc: 'New York',
};

// Resolve a city + state to a Government ID. Tries city+state (state may be an
// abbreviation or full name — the lookup carries both) then city-only, then
// the same via a known alias (e.g. Brooklyn → New York).
export function lookupGovId(city, state, cityLookup = CITY_LOOKUP) {
  const c = String(city || '').trim();
  const s = String(state || '').trim();
  if (!c) return null;
  const tryCity = (name) => {
    for (const k of [normKey(name + s), normKey(name)]) if (cityLookup[k] != null) return cityLookup[k];
    return null;
  };
  const direct = tryCity(c);
  if (direct != null) return direct;
  const alias = CITY_ALIASES[normKey(c)];
  return alias ? tryCity(alias) : null;
}

export function getMandates(govId, ordinances = MASTER_ORDINANCES) {
  if (!govId) return null;
  return ordIndex(ordinances).get(govId) || null;
}

// Classify a property type into the threshold bucket the ordinances use.
export function classifyPropertyType(propertyType) {
  const p = String(propertyType || '').toLowerCase();
  if (/multi.?family|apartment|residenc|dormitory|dwelling|housing/.test(p)) return 'multifamily';
  if (/government|public|civic|courthouse|library|police|fire\s*station|city\s*hall|municipal|school|university|college|museum/.test(p)) return 'public';
  return 'nonresidential';
}

// Pick the applicable ft² threshold for a category given the property-type
// bucket, falling back to whatever threshold the ordinance does define.
function thresholdFor(category, mandate, ptClass) {
  const t = mandate[category].thresholds || {};
  let order;
  if (category === 'bbs') {
    order = ptClass === 'public' ? ['public', 'nonResidential', 'statewide']
      : ptClass === 'multifamily' ? ['multiFamily', 'nonResidential', 'statewide']
      : ['nonResidential', 'statewide', 'public'];
  } else if (category === 'audits') {
    order = ptClass === 'public' ? ['public', 'commercial']
      : ptClass === 'multifamily' ? ['multifamily', 'commercial']
      : ['commercial', 'public'];
  } else { // bps
    order = ptClass === 'multifamily' ? ['multiFamily', 'nonResidential'] : ['nonResidential', 'multiFamily'];
  }
  for (const key of order) if (t[key] != null) return t[key];
  // Last resort: any defined threshold.
  for (const v of Object.values(t)) if (v != null) return v;
  return null;
}

// Evaluate one category for one site. `site`: { sqft, propertyType }.
// Returns { applicable, active, eligible, threshold, deadline, penalty, ... }.
//   eligible: true | false | null (unknown — no square footage, or the
//             ordinance defines no usable threshold for this property type).
function evalCategory(category, mandate, site) {
  const cat = mandate[category];
  if (!cat || !cat.active) {
    return { category, applicable: false, active: false, eligible: false };
  }
  const ptClass = classifyPropertyType(site.propertyType);
  const threshold = thresholdFor(category, mandate, ptClass);
  const sqft = Number.isFinite(site.sqft) ? site.sqft : null;
  // Applicability follows the active ordinance ONLY — the ft² threshold is
  // reported as a requirement but does not gate applicability. `meetsThreshold`
  // is kept purely as informational context (true/false/null-unknown).
  const meetsThreshold = (sqft == null || threshold == null) ? null : sqft >= threshold;
  return {
    category,
    applicable: true,
    active: true,
    eligible: true,          // active ordinance => applicable, regardless of size
    threshold,
    meetsThreshold,
    ptClass,
    deadline: cat.deadline || null,
    deadlineRaw: cat.deadlineRaw || null,
    penalty: cat.maxPenalty ?? null,
    policyName: cat.policyName || cat.ordinanceName || '',
    status: cat.status || '',
  };
}

// Screen one site end-to-end. `site`: { id, siteName, city, state, sqft,
// propertyType, electricUtility, gasUtility }. Never throws.
export function screenSite(site, { ordinances = MASTER_ORDINANCES, cityLookup = CITY_LOOKUP } = {}) {
  const govId = lookupGovId(site.city, site.state, cityLookup);
  const mandate = getMandates(govId, ordinances);
  if (!mandate) {
    return { ...site, matched: false, govId: govId || null, government: null };
  }
  const out = { ...site, matched: true, govId, government: mandate.government, mandateState: mandate.state };
  for (const c of CATEGORIES) out[c] = evalCategory(c, mandate, site);
  return out;
}

export function screenSites(sites, opts) {
  return (sites || []).map(s => screenSite(s, opts));
}

// Human label for the company / portfolio a compliance site list belongs to,
// taken from each site's Company Name (mapped on the Utility Lookup upload).
// One distinct company → that name; a couple → both; more → the first plus a
// "+N more" tag; none → '' so callers can hide the line.
export function sitesCompanyLabel(sites) {
  const names = [];
  const seen = new Set();
  for (const s of (sites || [])) {
    const c = String(s?.company || '').trim();
    if (!c) continue;
    const k = c.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    names.push(c);
  }
  if (names.length === 0) return '';
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} & ${names[1]}`;
  return `${names[0]} +${names.length - 1} more`;
}

// ---- Aggregations for the dashboard / report -----------------------------
// All operate on the output of screenSites(). A site "counts" for a category
// when eligible === true.

const isEligible = (r, c) => r.matched && r[c] && r[c].eligible === true;

// Count of eligible sites grouped by jurisdiction (Government), for a category.
export function eligibilityByOrdinance(results, category) {
  const m = new Map();
  for (const r of results) if (isEligible(r, category)) m.set(r.government, (m.get(r.government) || 0) + 1);
  return [...m.entries()].map(([government, count]) => ({ government, count })).sort((a, b) => b.count - a.count);
}

export function totalEligible(results, category) {
  return results.reduce((n, r) => n + (isEligible(r, category) ? 1 : 0), 0);
}

// Eligible-site count per compliance deadline (for the timeline charts).
export function deadlinesByDate(results, category) {
  const m = new Map();
  for (const r of results) {
    if (!isEligible(r, category)) continue;
    const d = r[category].deadline;
    if (!d) continue;
    m.set(d, (m.get(d) || 0) + 1);
  }
  return [...m.entries()].map(([date, count]) => ({ date, count })).sort((a, b) => a.date.localeCompare(b.date));
}

// Estimated max yearly penalty summed over eligible sites, grouped by
// jurisdiction (per-site penalty × eligible sites in that jurisdiction).
export function penaltyByOrdinance(results, category) {
  const m = new Map();
  for (const r of results) {
    if (!isEligible(r, category)) continue;
    const p = r[category].penalty;
    if (p == null) continue;
    m.set(r.government, (m.get(r.government) || 0) + p);
  }
  return [...m.entries()].map(([government, penalty]) => ({ government, penalty })).sort((a, b) => b.penalty - a.penalty);
}

export function totalPenalty(results, category) {
  return penaltyByOrdinance(results, category).reduce((n, x) => n + x.penalty, 0);
}

// ---- BPS Prioritization ---------------------------------------------------
// A focused BPS view grouped by (deadline, jurisdiction): the fine for
// exceeding performance limits, how many sites are eligible, and the summed
// estimated non-reporting penalty. Surfaced on the Master Analysis overview,
// both compliance exports, and the on-page screening tab.

// "BPS Fines for Exceeding Limits" label from a jurisdiction's raw fields,
// e.g. "62000 $/year", "0.35 $/kBtu", "270 $/Metric ton/ CO2e", or "N/A".
function bpsExceedFineLabel(mandate) {
  const raw = mandate?.raw || {};
  const costRaw = raw['BPS - Enforcement Cost (Exceed limits)'];
  const uomRaw = raw['BPS - Enforcement UOM (Exceed Limits)'];
  const cost = costRaw == null ? '' : String(costRaw).trim();
  const uom = uomRaw == null ? '' : String(uomRaw).trim();
  const costBlank = cost === '' || Number(cost) === 0;
  const uomBlank = uom === '' || uom.toUpperCase() === 'N/A';
  if (costBlank && uomBlank) return 'N/A';
  if (costBlank) return uom || 'N/A';
  return [cost, uomBlank ? '' : uom].filter(Boolean).join(' ');
}

// Per-site estimated BPS non-reporting penalty, respecting the jurisdiction's
// penalty UOM: a "$ per SqFt/Year" penalty scales by building size; anything
// else is a flat annual amount. Returns null when it can't be computed (no
// penalty defined, or a size-based penalty with unknown square footage).
export function bpsNonReportingPenalty(bpsMandate, sqft) {
  const cost = bpsMandate?.maxPenalty;
  if (cost == null) return null;
  const uom = String(bpsMandate?.penaltyUom || '').toLowerCase();
  const perSqft = /sq\s*\.?\s*ft|sqft|\/\s*sf\b/.test(uom);
  if (perSqft) return Number.isFinite(sqft) ? cost * sqft : null;
  return cost;
}

// BPS prioritization rows: one per (deadline, government) across BPS-eligible
// sites, sorted by deadline (undated last) then government. `penalty` is the
// summed estimated non-reporting exposure; `penaltyKnown` is false when no
// site in the group had a computable penalty (so callers can show a dash).
export function bpsPrioritization(results, ordinances = MASTER_ORDINANCES) {
  const m = new Map();
  for (const r of (results || [])) {
    if (!isEligible(r, 'bps')) continue;
    const mandate = getMandates(r.govId, ordinances);
    const deadline = r.bps.deadline || null;
    const government = r.government || mandate?.government || '';
    const key = `${deadline || ''}||${government}`;
    let g = m.get(key);
    if (!g) {
      g = {
        deadline,
        deadlineRaw: r.bps.deadlineRaw || null,
        government,
        fine: bpsExceedFineLabel(mandate),
        sites: 0,
        penalty: 0,
        penaltyKnown: false,
        feeExceeding: 'TBD (Full Screening Analysis Needed)',
      };
      m.set(key, g);
    }
    g.sites += 1;
    const p = bpsNonReportingPenalty(mandate?.bps, r.sqft);
    if (p != null) { g.penalty += p; g.penaltyKnown = true; }
  }
  return [...m.values()].sort((a, b) => {
    const ad = a.deadline || '9999-12-31';
    const bd = b.deadline || '9999-12-31';
    if (ad !== bd) return ad.localeCompare(bd);
    return String(a.government).localeCompare(String(b.government));
  });
}

// Whole-Building Utility Data Collection eligibility: sites eligible for BBS or
// BPS, grouped by state → utility, for a commodity ('electric' | 'gas').
export function utilityFeedEligibility(results, commodity) {
  const utilKey = commodity === 'gas' ? 'gasUtility' : 'electricUtility';
  const byState = new Map();
  let total = 0;
  for (const r of results) {
    if (!(isEligible(r, 'bbs') || isEligible(r, 'bps'))) continue;
    const util = String(r[utilKey] || '').trim();
    if (!util) continue;
    const st = String(r.mandateState || r.state || '').trim();
    if (!byState.has(st)) byState.set(st, new Map());
    const u = byState.get(st);
    u.set(util, (u.get(util) || 0) + 1);
    total++;
  }
  const rows = [];
  for (const [state, utils] of byState) {
    for (const [utility, count] of utils) rows.push({ state, utility, count });
  }
  rows.sort((a, b) => a.state.localeCompare(b.state) || b.count - a.count);
  return { total, rows };
}

// ---- Compliance Roadmap: obligations, sites, and fine exposure over time --
// Turns the screened sites into a quarter-by-quarter timeline: how many new
// compliance deadlines land each quarter (by category), how the count of
// distinct sites carrying an obligation grows, and how the cumulative max
// yearly fine exposure ramps up. Powers the Compliance Roadmap subtab.

function quarterOf(iso) {
  const [y, m] = String(iso).split('-').map(Number);
  const q = Math.floor((m - 1) / 3) + 1;
  return { sort: y * 4 + (q - 1), label: `Q${q} ${y}` };
}
function labelOfSort(sort) {
  const y = Math.floor(sort / 4);
  const q = (sort % 4) + 1;
  return { key: `${y}-Q${q}`, label: `Q${q} ${y}`, startISO: `${y}-${String((q - 1) * 3 + 1).padStart(2, '0')}-01` };
}

// results: output of screenSites(). Returns quarterly periods (spanning the
// first → last dated deadline) plus totals. A site counts toward "sites in
// scope" from its EARLIEST dated deadline; each (site, category) obligation
// adds its max yearly penalty at its own deadline. Obligations that are active
// but have no parseable deadline are tallied under `undated` (not placed on
// the timeline).
export function buildComplianceRoadmap(results) {
  const events = [];
  const siteEarliestSort = new Map();
  let undated = 0;
  for (const r of (results || [])) {
    if (!r.matched) continue;
    for (const c of CATEGORIES) {
      const e = r[c];
      if (!e || !e.active) continue;
      if (!e.deadline) { undated++; continue; }
      const q = quarterOf(e.deadline);
      events.push({ siteId: r.id, category: c, penalty: e.penalty || 0, sort: q.sort });
      const prev = siteEarliestSort.get(r.id);
      if (prev == null || q.sort < prev) siteEarliestSort.set(r.id, q.sort);
    }
  }
  const totals = {
    sites: siteEarliestSort.size,
    obligations: events.length,
    fines: events.reduce((n, e) => n + e.penalty, 0),
    undated,
  };
  if (!events.length) return { periods: [], totals };

  const newSitesBySort = new Map();
  for (const s of siteEarliestSort.values()) newSitesBySort.set(s, (newSitesBySort.get(s) || 0) + 1);
  const aggBySort = new Map();
  for (const ev of events) {
    let a = aggBySort.get(ev.sort);
    if (!a) { a = { fines: 0, oblig: 0, byCat: { bbs: 0, audits: 0, bps: 0 } }; aggBySort.set(ev.sort, a); }
    a.fines += ev.penalty; a.oblig++; a.byCat[ev.category]++;
  }

  const sorts = events.map(e => e.sort);
  const minS = Math.min(...sorts), maxS = Math.max(...sorts);
  const periods = [];
  let cumSites = 0, cumFines = 0, cumOblig = 0;
  const cumByCat = { bbs: 0, audits: 0, bps: 0 };
  for (let s = minS; s <= maxS; s++) {
    const a = aggBySort.get(s) || { fines: 0, oblig: 0, byCat: { bbs: 0, audits: 0, bps: 0 } };
    const newSites = newSitesBySort.get(s) || 0;
    cumSites += newSites; cumFines += a.fines; cumOblig += a.oblig;
    for (const c of CATEGORIES) cumByCat[c] += a.byCat[c];
    const meta = labelOfSort(s);
    periods.push({
      ...meta,
      newSites, cumSites,
      newObligations: a.oblig, cumObligations: cumOblig,
      newByCategory: { ...a.byCat },
      cumByCategory: { ...cumByCat },
      newFines: a.fines, cumFines,
    });
  }
  return { periods, totals };
}
