// Building Compliance Screening — two-step lookup + eligibility.
//
//   site (city, state, sq ft, property type)
//        │  1. City Lookup:  normalized city+state → Government ID
//        ▼
//   Government ID
//        │  2. Master Ordinances:  Government ID → BBS / Audits / BPS mandates
//        ▼
//   per-category eligibility (active ordinance AND building ≥ the size
//   threshold for its property type), the compliance deadline, and the
//   estimated max yearly penalty.
//
// The two reference tables are committed seeds (src/data/masterOrdinances.js
// and src/data/complianceCityLookup.js), generated by
// scripts/buildComplianceOrdinances.mjs. Callers may pass a replacement pair
// (e.g. a user-uploaded City Lookup + Master Ordinances) to every function.

import MASTER_ORDINANCES from '../data/masterOrdinances.js';
import CITY_LOOKUP from '../data/complianceCityLookup.js';

export const CATEGORIES = ['bbs', 'audits', 'bps'];
export const CATEGORY_LABEL = { bbs: 'BBS', audits: 'Energy Audits', bps: 'BPS' };
// Brand-ish palette matching the example deliverable: BBS blue, Audits
// orange, BPS green (+ utility-feed gold / crimson on page 3).
export const CATEGORY_COLOR = { bbs: '#29ABE2', audits: '#F7941E', bps: '#3DAE2B' };

export function normKey(s) {
  return String(s == null ? '' : s).toLowerCase().replace(/[^a-z0-9]+/g, '');
}

// Index the ordinances list by Government ID once per (list identity).
const _ordIndexCache = new WeakMap();
function ordIndex(ordinances) {
  let m = _ordIndexCache.get(ordinances);
  if (!m) { m = new Map(ordinances.map(g => [g.govId, g])); _ordIndexCache.set(ordinances, m); }
  return m;
}

// Common member-city / alias → the jurisdiction city named in the ordinances,
// so a site whose city is a borough (or a covered municipality) still resolves
// to the governing jurisdiction. This is a curated stopgap for the derived
// City Lookup — the real City Lookup tab would carry these mappings directly.
export const CITY_ALIASES = {
  // New York City boroughs all fall under the NYC ordinances.
  brooklyn: 'New York', bronx: 'New York', queens: 'New York',
  statenisland: 'New York', manhattan: 'New York',
  newyorkcity: 'New York', nyc: 'New York',
};

// Resolve a city + state to a Government ID. Tries city+state (state may be an
// abbreviation or full name — the lookup carries both) then city-only, then
// the same via a known alias (e.g. Brooklyn → New York).
export function lookupGovId(city, state, cityLookup = CITY_LOOKUP) {
  const c = String(city || '').trim();
  const s = String(state || '').trim();
  if (!c) return null;
  const tryCity = (name) => {
    for (const k of [normKey(name + s), normKey(name)]) if (cityLookup[k] != null) return cityLookup[k];
    return null;
  };
  const direct = tryCity(c);
  if (direct != null) return direct;
  const alias = CITY_ALIASES[normKey(c)];
  return alias ? tryCity(alias) : null;
}

export function getMandates(govId, ordinances = MASTER_ORDINANCES) {
  if (!govId) return null;
  return ordIndex(ordinances).get(govId) || null;
}

// Classify a property type into the threshold bucket the ordinances use.
export function classifyPropertyType(propertyType) {
  const p = String(propertyType || '').toLowerCase();
  if (/multi.?family|apartment|residenc|dormitory|dwelling|housing/.test(p)) return 'multifamily';
  if (/government|public|civic|courthouse|library|police|fire\s*station|city\s*hall|municipal|school|university|college|museum/.test(p)) return 'public';
  return 'nonresidential';
}

// Pick the applicable ft² threshold for a category given the property-type
// bucket, falling back to whatever threshold the ordinance does define.
function thresholdFor(category, mandate, ptClass) {
  const t = mandate[category].thresholds || {};
  let order;
  if (category === 'bbs') {
    order = ptClass === 'public' ? ['public', 'nonResidential', 'statewide']
      : ptClass === 'multifamily' ? ['multiFamily', 'nonResidential', 'statewide']
      : ['nonResidential', 'statewide', 'public'];
  } else if (category === 'audits') {
    order = ptClass === 'public' ? ['public', 'commercial']
      : ptClass === 'multifamily' ? ['multifamily', 'commercial']
      : ['commercial', 'public'];
  } else { // bps
    order = ptClass === 'multifamily' ? ['multiFamily', 'nonResidential'] : ['nonResidential', 'multiFamily'];
  }
  for (const key of order) if (t[key] != null) return t[key];
  // Last resort: any defined threshold.
  for (const v of Object.values(t)) if (v != null) return v;
  return null;
}

// Evaluate one category for one site. `site`: { sqft, propertyType }.
// Returns { applicable, active, eligible, threshold, deadline, penalty, ... }.
//   eligible: true | false | null (unknown — no square footage, or the
//             ordinance defines no usable threshold for this property type).
function evalCategory(category, mandate, site) {
  const cat = mandate[category];
  if (!cat || !cat.active) {
    return { category, applicable: false, active: false, eligible: false };
  }
  const ptClass = classifyPropertyType(site.propertyType);
  const threshold = thresholdFor(category, mandate, ptClass);
  const sqft = Number.isFinite(site.sqft) ? site.sqft : null;
  // Applicability follows the active ordinance ONLY — the ft² threshold is
  // reported as a requirement but does not gate applicability. `meetsThreshold`
  // is kept purely as informational context (true/false/null-unknown).
  const meetsThreshold = (sqft == null || threshold == null) ? null : sqft >= threshold;
  return {
    category,
    applicable: true,
    active: true,
    eligible: true,          // active ordinance => applicable, regardless of size
    threshold,
    meetsThreshold,
    ptClass,
    deadline: cat.deadline || null,
    deadlineRaw: cat.deadlineRaw || null,
    penalty: cat.maxPenalty ?? null,
    policyName: cat.policyName || cat.ordinanceName || '',
    status: cat.status || '',
  };
}

// Screen one site end-to-end. `site`: { id, siteName, city, state, sqft,
// propertyType, electricUtility, gasUtility }. Never throws.
export function screenSite(site, { ordinances = MASTER_ORDINANCES, cityLookup = CITY_LOOKUP } = {}) {
  const govId = lookupGovId(site.city, site.state, cityLookup);
  const mandate = getMandates(govId, ordinances);
  if (!mandate) {
    return { ...site, matched: false, govId: govId || null, government: null };
  }
  const out = { ...site, matched: true, govId, government: mandate.government, mandateState: mandate.state };
  for (const c of CATEGORIES) out[c] = evalCategory(c, mandate, site);
  return out;
}

export function screenSites(sites, opts) {
  return (sites || []).map(s => screenSite(s, opts));
}

// ---- Aggregations for the dashboard / report -----------------------------
// All operate on the output of screenSites(). A site "counts" for a category
// when eligible === true.

const isEligible = (r, c) => r.matched && r[c] && r[c].eligible === true;

// Count of eligible sites grouped by jurisdiction (Government), for a category.
export function eligibilityByOrdinance(results, category) {
  const m = new Map();
  for (const r of results) if (isEligible(r, category)) m.set(r.government, (m.get(r.government) || 0) + 1);
  return [...m.entries()].map(([government, count]) => ({ government, count })).sort((a, b) => b.count - a.count);
}

export function totalEligible(results, category) {
  return results.reduce((n, r) => n + (isEligible(r, category) ? 1 : 0), 0);
}

// Eligible-site count per compliance deadline (for the timeline charts).
export function deadlinesByDate(results, category) {
  const m = new Map();
  for (const r of results) {
    if (!isEligible(r, category)) continue;
    const d = r[category].deadline;
    if (!d) continue;
    m.set(d, (m.get(d) || 0) + 1);
  }
  return [...m.entries()].map(([date, count]) => ({ date, count })).sort((a, b) => a.date.localeCompare(b.date));
}

// Estimated max yearly penalty summed over eligible sites, grouped by
// jurisdiction (per-site penalty × eligible sites in that jurisdiction).
export function penaltyByOrdinance(results, category) {
  const m = new Map();
  for (const r of results) {
    if (!isEligible(r, category)) continue;
    const p = r[category].penalty;
    if (p == null) continue;
    m.set(r.government, (m.get(r.government) || 0) + p);
  }
  return [...m.entries()].map(([government, penalty]) => ({ government, penalty })).sort((a, b) => b.penalty - a.penalty);
}

export function totalPenalty(results, category) {
  return penaltyByOrdinance(results, category).reduce((n, x) => n + x.penalty, 0);
}

// Whole-Building Utility Data Collection eligibility: sites eligible for BBS or
// BPS, grouped by state → utility, for a commodity ('electric' | 'gas').
export function utilityFeedEligibility(results, commodity) {
  const utilKey = commodity === 'gas' ? 'gasUtility' : 'electricUtility';
  const byState = new Map();
  let total = 0;
  for (const r of results) {
    if (!(isEligible(r, 'bbs') || isEligible(r, 'bps'))) continue;
    const util = String(r[utilKey] || '').trim();
    if (!util) continue;
    const st = String(r.mandateState || r.state || '').trim();
    if (!byState.has(st)) byState.set(st, new Map());
    const u = byState.get(st);
    u.set(util, (u.get(util) || 0) + 1);
    total++;
  }
  const rows = [];
  for (const [state, utils] of byState) {
    for (const [utility, count] of utils) rows.push({ state, utility, count });
  }
  rows.sort((a, b) => a.state.localeCompare(b.state) || b.count - a.count);
  return { total, rows };
}
