// Prep script: turn the "Whole Building Data By Utility" workbook into the
// committed seeds the app bundles:
//
//   src/data/wholeBuildingUtilities.js     — the table itself, column-compressed.
//   src/data/wholeBuildingUtilitiesMeta.js — just the row / zip / utility counts.
//
// Two files on purpose. The table is ~70k rows and is only needed when someone
// clicks the download, so the screening page dynamic-imports it and Vite keeps
// it out of the main chunk. The header line still wants the counts at render
// time, and importing them from the big module would pull the whole thing back
// into the eager bundle — hence the tiny companion.
//
// Regenerate:  node scripts/buildWholeBuildingUtilities.mjs <path-to-WholeBuildingData.xlsx|.csv>
// The raw workbook is not committed; only the processed seed is, so the app
// runs offline, same as the City Lookup and Master Ordinances seeds.
//
// Shape: every column except Zip Code, State and "Predominant Utility?" is a
// property of the utility, not the zip code — 70,824 rows carry only 2,137
// distinct utility records between them. So the utility rows are interned once
// and the zip rows are grouped by (utility, state, predominant) with their zip
// codes packed into one space-joined string. That is ~10x smaller than a row
// per line, and expandRows() puts the original rows back for the download.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import * as XLSX from 'xlsx';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IN = process.argv[2];
if (!IN) {
  console.error('Usage: node scripts/buildWholeBuildingUtilities.mjs <WholeBuildingData.xlsx>');
  process.exit(1);
}
const OUT = path.join(__dirname, '..', 'src', 'data', 'wholeBuildingUtilities.js');
const OUT_META = path.join(__dirname, '..', 'src', 'data', 'wholeBuildingUtilitiesMeta.js');

const clean = (v) => String(v ?? '').replace(/\s+/g, ' ').trim();

// The workbook's column order, which the download reproduces.
const COLUMNS = [
  'Zip Code', 'State', 'Utility Name', 'Utility Code', 'Predominant Utility?',
  'Electric?', 'Gas?', 'Steam?', 'Water?', 'Data Type',
  'Aggregate Whole-Building Data?', 'Multifamily Included?',
  'Contact Person', 'Contact Phone', 'Contact Email', 'Website',
];
// Everything the utility owns — COLUMNS minus the three that vary by zip row.
const UTIL_COLUMNS = COLUMNS.filter(c => c !== 'Zip Code' && c !== 'State' && c !== 'Predominant Utility?');

function main() {
  // XLSX.readFile isn't bound to fs in the ESM build; read the bytes ourselves.
  const wb = XLSX.read(fs.readFileSync(IN), { type: 'buffer', raw: true });
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval: '' });

  const states = [];
  const stateIdx = new Map();
  const utils = [];
  const utilIdx = new Map();
  // (utilIdx, stateIdx, predominant) -> zip codes, in first-seen order so the
  // download comes out in the workbook's own order rather than a sorted one.
  const groups = new Map();
  const report = { rows: rows.length, noZip: 0 };

  for (const r of rows) {
    // A zip is the row's key; without one it can't be looked up or grouped.
    // Excel drops the leading zero on New England zips, so pad back to 5.
    const zip = clean(r['Zip Code']).padStart(5, '0');
    if (!zip) { report.noZip++; continue; }

    const state = clean(r.State);
    if (!stateIdx.has(state)) { stateIdx.set(state, states.length); states.push(state); }

    const util = UTIL_COLUMNS.map(c => clean(r[c]));
    const uKey = JSON.stringify(util);
    if (!utilIdx.has(uKey)) { utilIdx.set(uKey, utils.length); utils.push(util); }

    // "Yes" / "No" — stored as 1 / 0, and anything else reads as not predominant.
    const predominant = /^y/i.test(clean(r['Predominant Utility?'])) ? 1 : 0;
    const gKey = `${utilIdx.get(uKey)}|${stateIdx.get(state)}|${predominant}`;
    if (!groups.has(gKey)) {
      groups.set(gKey, { u: utilIdx.get(uKey), s: stateIdx.get(state), p: predominant, zips: [] });
    }
    groups.get(gKey).zips.push(zip);
  }

  const groupRows = [...groups.values()].map(g => [g.u, g.s, g.p, g.zips.join(' ')]);
  const rowCount = groupRows.reduce((n, g) => n + g[3].split(' ').length, 0);
  const zipCount = new Set(groupRows.flatMap(g => g[3].split(' '))).size;

  const src = `// AUTO-GENERATED by scripts/buildWholeBuildingUtilities.mjs — do not edit by hand.
// Whole Building Data By Utility: which utility serves a zip code, and whether
// that utility publishes aggregated whole-building data — the feed a site needs
// before it can benchmark against the mandates screened on this page.
//
// Stored column-compressed: the utility columns are interned (every column
// except Zip Code, State and Predominant Utility? belongs to the utility, not
// the zip), and the zip rows are grouped by utility + state + predominant flag
// with the zips packed into one space-joined string. Call expandRows() for the
// workbook's own rows back.
//
// Only imported where the table is actually needed — the screening page
// dynamic-imports it inside the download handler so it stays out of the main
// bundle. Import the counts from ./wholeBuildingUtilitiesMeta.js instead.

// The workbook's column order, which the download reproduces.
export const COLUMNS = ${JSON.stringify(COLUMNS)};

// State / province abbreviations, indexed by GROUPS[1].
export const STATES = ${JSON.stringify(states)};

// The columns a utility owns — COLUMNS minus the three that vary by zip row.
// UTILITIES rows are in this order.
export const UTIL_COLUMNS = ${JSON.stringify(UTIL_COLUMNS)};

// One row per distinct utility record, in UTIL_COLUMNS order.
export const UTILITIES = ${JSON.stringify(utils)};

// [index into UTILITIES, index into STATES, predominant 1|0, space-joined zips].
export const GROUPS = ${JSON.stringify(groupRows)};

// The workbook's rows, rebuilt as plain objects keyed by COLUMNS. Built on
// demand rather than at import: nothing needs them until a download asks.
export function expandRows() {
  const out = [];
  for (const [u, s, p, zips] of GROUPS) {
    const util = UTILITIES[u];
    const state = STATES[s];
    const predominant = p ? 'Yes' : 'No';
    for (const zip of zips.split(' ')) {
      const row = { 'Zip Code': zip, 'State': state, 'Predominant Utility?': predominant };
      UTIL_COLUMNS.forEach((c, i) => { row[c] = util[i]; });
      // Re-keyed into the workbook's column order — json_to_sheet takes its
      // column order from the first object's keys, not from a header list.
      const ordered = {};
      for (const c of COLUMNS) ordered[c] = row[c];
      out.push(ordered);
    }
  }
  return out;
}

export default GROUPS;
`;
  fs.writeFileSync(OUT, src);

  const meta = `// AUTO-GENERATED by scripts/buildWholeBuildingUtilities.mjs — do not edit by hand.
// Just the size of ./wholeBuildingUtilities.js, for the header line that cites
// the table without needing to load it. Kept separate so the ~70k-row seed
// stays out of the main bundle — see that file's note.
export const WHOLE_BUILDING_META = ${JSON.stringify({ rows: rowCount, zips: zipCount, utilities: utils.length, states: states.length })};
export default WHOLE_BUILDING_META;
`;
  fs.writeFileSync(OUT_META, meta);

  const kb = (p) => `${(fs.statSync(p).size / 1024).toFixed(0)} KB`;
  console.log(`Wrote ${rowCount.toLocaleString()} rows / ${zipCount.toLocaleString()} zips / ${utils.length.toLocaleString()} utilities / ${states.length} states`);
  console.log(`  ${path.relative(process.cwd(), OUT)} (${kb(OUT)}) · ${path.relative(process.cwd(), OUT_META)} (${kb(OUT_META)})`);
  console.log(`  source rows ${report.rows.toLocaleString()} · no zip ${report.noZip} · groups ${groupRows.length.toLocaleString()}`);
}

main();
