// One-off prep script: turn EPA's ZIP -> electric utility crosswalk into the
// compact table the app bundles (src/data/eiaZipUtilities.js), so the Utility
// Lookup page can name a US site's electric utility from its zip without the
// user uploading a utility file first.
//
// SOURCE (MIT-licensed, US EPA), the same file buildEgridCrosswalk.mjs reads:
//   https://github.com/USEPA/power-profiler  ->  app/data/zip.csv
//   Columns: zip,state,eiaid,UtilName,SUBRGN,Predominant Utility
// The utility columns come from EIA Form 861 service territories; every zip
// carries exactly one row flagged Predominant Utility = 1, and that is the
// one kept. The raw crosswalk is NOT committed. To regenerate:
//   git clone --depth 1 https://github.com/USEPA/power-profiler
//   node scripts/buildEiaZipUtilities.mjs power-profiler/app/data/zip.csv
//
// Output: a names list and a zip -> index map, so the ~1,500 distinct
// utility names aren't repeated across ~41,000 zips.
//
// Names are tidied for display: EIA appends the parent company in brackets
// ("Connecticut Light & Power Co (The) [Eversource Energy]") and tags some
// names with their state ("Town of Reading - (MA)"). Both go; the
// classifier in utilityClassify.js reads municipals / coops off what is left.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IN = process.argv[2] || path.join(__dirname, '..', 'power-profiler', 'app', 'data', 'zip.csv');
const OUT = path.join(__dirname, '..', 'src', 'data', 'eiaZipUtilities.js');

// Minimal RFC 4180 CSV parser: UtilName carries quoted commas
// ("UNS Electric, Inc").
function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

export function tidyUtilityName(raw) {
  return String(raw || '')
    .replace(/\s*\[[^\]]*\]\s*$/, '')
    .replace(/\s*-?\s*\([A-Z]{2}\)\s*$/, '')
    .replace(/\s*\(The\)/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function main() {
  const text = fs.readFileSync(IN, 'utf8').replace(/^﻿/, '');
  const [header, ...rows] = parseCSV(text);
  const col = (name) => header.indexOf(name);
  const iZip = col('zip');
  const iName = col('UtilName');
  const iPred = col('Predominant Utility');
  if (iZip < 0 || iName < 0 || iPred < 0) throw new Error(`unexpected header: ${header.join(',')}`);

  const names = [];
  const nameIndex = new Map();
  const zipMap = {};
  for (const r of rows) {
    if (r[iPred] !== '1') continue;
    const zip = String(r[iZip] || '').trim().padStart(5, '0');
    const name = tidyUtilityName(r[iName]);
    if (!/^\d{5}$/.test(zip) || !name) continue;
    let idx = nameIndex.get(name);
    if (idx == null) { idx = names.length; names.push(name); nameIndex.set(name, idx); }
    zipMap[zip] = idx;
  }

  const zips = Object.keys(zipMap).sort();
  const body = zips.map(z => `"${z}":${zipMap[z]}`).join(',');
  const out = `// GENERATED by scripts/buildEiaZipUtilities.mjs from EPA's power-profiler
// ZIP crosswalk (EIA Form 861 service territories, MIT-licensed). Do not
// edit by hand; regenerate instead. ${zips.length} zips, ${names.length} utilities.
export const EIA_UTILITY_NAMES = ${JSON.stringify(names)};
export const EIA_ZIP_UTILITY = {${body}};
`;
  fs.writeFileSync(OUT, out);
  console.log(`wrote ${OUT}: ${zips.length} zips, ${names.length} utilities, ${(out.length / 1024).toFixed(0)} KB`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
