// One-off prep script: turn EPA's eGRID "Power Profiler" ZIP crosswalk into
// the compact seed the app bundles (src/data/egridZipSubregions.json).
//
// SOURCE (MIT-licensed, US EPA):
//   https://github.com/USEPA/power-profiler  ->  app/data/zip.csv
//   Columns: zip,state,eiaid,UtilName,SUBRGN,Predominant Utility
// The raw crosswalk (~65k rows / ~3 MB) is NOT committed; only the processed
// seed is, so the app works offline without ever fetching at runtime. To
// regenerate after an eGRID release:
//   git clone --depth 1 https://github.com/USEPA/power-profiler
//   node scripts/buildEgridCrosswalk.mjs power-profiler/app/data/zip.csv
//
// Output format: { "<5-digit zip>": "PRED|OTHER|..." } — the predominant
// eGRID subregion first, then any other distinct subregions the zip touches
// (seam detection happens at lookup time). Single-subregion zips are a bare
// string, e.g. "ERCT".

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IN = process.argv[2] || path.join(__dirname, '..', 'power-profiler', 'app', 'data', 'zip.csv');
// Emitted as a .js ESM module (not .json) so both the Vite bundle and the
// plain-Node test can `import` it without JSON import-attribute friction.
const OUT = path.join(__dirname, '..', 'src', 'data', 'egridZipSubregions.js');

// Minimal RFC 4180 CSV parser — the crosswalk's UtilName column contains
// quoted commas, so a naive split on ',' corrupts the SUBRGN column.
function parseCSV(text) {
  text = text.replace(/^﻿/, ''); // strip BOM
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false; }
      else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c === '\r') { /* skip */ }
    else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

// Same normalization the app applies (see normalizeZip in utilityRatesStore /
// isoLookup): strip to digits, keep first 5, zero-pad short (Northeast) zips.
function normZip(v) {
  const digits = String(v ?? '').trim().split('-')[0].replace(/\D/g, '');
  if (!digits) return '';
  return digits.length >= 5 ? digits.slice(0, 5) : digits.padStart(5, '0');
}

function main() {
  const rows = parseCSV(fs.readFileSync(IN, 'utf8'));
  const header = rows[0].map(h => h.trim());
  const iZip = header.indexOf('zip');
  const iSub = header.indexOf('SUBRGN');
  const iPred = header.indexOf('Predominant Utility');
  if (iZip < 0 || iSub < 0 || iPred < 0) {
    throw new Error(`Unexpected header: ${header.join(',')}`);
  }

  // zip -> { subs: ordered unique subregion list, pred: predominant subregion }
  const byZip = new Map();
  for (let r = 1; r < rows.length; r++) {
    const row = rows[r];
    if (row.length <= iPred) continue;
    const zip = normZip(row[iZip]);
    const sub = String(row[iSub] || '').trim();
    if (!zip || !sub) continue;
    const isPred = String(row[iPred]).trim() === '1';
    let e = byZip.get(zip);
    if (!e) { e = { subs: [], pred: null }; byZip.set(zip, e); }
    if (!e.subs.includes(sub)) e.subs.push(sub);
    if (isPred) e.pred = sub;
  }

  const out = {};
  let multi = 0, noPred = 0;
  for (const [zip, e] of byZip) {
    const pred = e.pred || e.subs[0];
    if (!e.pred) noPred++;
    const ordered = [pred, ...e.subs.filter(s => s !== pred)];
    if (ordered.length > 1) multi++;
    out[zip] = ordered.join('|');
  }

  // Stable key order keeps the committed diff clean across regenerations.
  const sorted = {};
  for (const k of Object.keys(out).sort()) sorted[k] = out[k];
  const banner = '// AUTO-GENERATED by scripts/buildEgridCrosswalk.mjs — do not edit by hand.\n'
    + '// Source: EPA eGRID Power Profiler ZIP crosswalk (github.com/USEPA/power-profiler, MIT).\n'
    + '// Map of 5-digit ZIP -> predominant-first, pipe-joined eGRID subregion code(s).\n';
  fs.writeFileSync(OUT, `${banner}export default ${JSON.stringify(sorted)};\n`);

  const bytes = fs.statSync(OUT).size;
  console.log(`Wrote ${Object.keys(sorted).length} zips to ${path.relative(process.cwd(), OUT)} (${(bytes / 1024).toFixed(0)} KB)`);
  console.log(`  multi-subregion zips: ${multi}${noPred ? `, zips with no predominant flag: ${noPred}` : ''}`);
}

main();
